name: masamune_module
description: Package in which various functions are modularized.
version: 0.8.5+44
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_module

environment:
  sdk: ">=2.13.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  masamune: ^0.8.0
  # masamune_ads: ^0.8.0
  share: ^2.0.0
  font_awesome_flutter: ^9.1.0
  photo_view: ^0.13.0
  flutter_quill: ^2.3.1
  sprintf: ^6.0.0
  tuple: ^2.0.0
  loading_animations: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  build_runner: ^2.0.4
  katana_module_builder: ^0.8.0
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
